### ISSUE TITLE
resumeページにおいてナビゲーションバーが自動で隠れない

### ISSUE THREAD

**Issue by narugit** [hiyoko3/hiyoko3.github.io#1]
[resumeページ](https://hiyoko3.github.io/resume)以外のページでは，スクロールを下に進めていくとナビゲーションバーが自動で隠れますが，当該ページでは自動で隠れません

**Comment by hiyoko3** [comment]
最新版では __resumeページ__ が __[productページ](https://hiyoko3.github.io/product)__ に変更されました．
こちらでも同様の問題が起きていますか？

加えて，まだresumeページが表示される場合は，一度ブラウザのキャッシュを削除してみてください．

**Comment by narugit** [comment]
**productページ**への変更を確認しました．
