### ISSUE TITLE
サイドメニューを非表示にできない

### ISSUE THREAD

**Issue by narugit** [hiyoko3/hiyoko3.github.io#2]
サイドメニューを表示後，ナビゲーションバーが自動で隠れた場合に，ハンバーガーメニューを押せないため，サイドメニューを非表示にできません．(1264 px~)
~1263 pxでは，サイドメニュー欄以外をクリックすることで非表示にすることができました．

該当ページは，以下の二つです．
- [topページ](https://hiyoko3.github.io)
- [skillページ](https://hiyoko3.github.io/skill)

**Comment by hiyoko3** [comment]
現在，ハンバーガーメニューは削除しています．

表示されている場合は，ブラウザがデータをキャッシュしていることが原因かと思われるので，
一度キャッシュを削除してからもう一度を確認してみてください．

**Comment by narugit** [comment]
ハンバーガーメニューの削除を確認しました．
